route:
# `group_wait` default is 30s, indicating the duration to hold off before sending an alert notification.
  group_wait: 5s
  receiver: webhook_receiver

receivers:
  - name: webhook_receiver
    webhook_configs:
      - url: 'https://webhook.site/#!/view/39ef270a-48bb-4490-8ce8-0f1390623041'
        send_resolved: false